title: Mohammad Ghaheri
description: Product, mobility and data notes by Mohammad Ghaheri.
url: https://mohammadghaheri.github.io
baseurl: ""
markdown: kramdown
permalink: /articles/:title/
timezone: Europe/Helsinki
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-sitemap
